[theme]
base = "light"
primaryColor = "#1C3D5A"
backgroundColor = "#FBFAF8"
secondaryBackgroundColor = "#F6F4F0"
textColor = "#14181F"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true

[browser]
gatherUsageStats = false
